### ISSUE TITLE
Repository Status?

### ISSUE THREAD

**Issue by eduncan911** [Guilouz/Klipper-Flsun-S1#2]
I see you making comments in other repositories and discord about the lack of developer access and how FLSun is changing stance on open source.

Could you post what the current state of this repository is?

- is it fully functional?
- how are you compiling and testing this custom version?  do u have some proprietary/protected access you can't share?  

Also, in general, how would one load this version of klipper?  since you typically need ssh access to perform these functions?

**Comment by Guilouz** [comment]
Please only post issue if is real issue.

Yes this repository is fully functional and tested but you can't use it as is.

We have already all access to the machine but if you want open source, ask to Flsun.
